package com.usta.formularios;

import com.usta.daos.DaoPersona;
import com.usta.entities.Persona;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.kordamp.ikonli.materialdesign2.MaterialDesignA;
import org.kordamp.ikonli.swing.FontIcon;

public class FrmRegistrar extends javax.swing.JFrame {

    FontIcon iconoRegresar = new FontIcon();

    public FrmRegistrar() {
        initComponents();

        setImageToLabel(lblImagen, "..\\proyectoFinalTerminado\\Imagenes\\Registro.png");

        iconoRegresar.setIkon(MaterialDesignA.ARROW_LEFT);
        iconoRegresar.setIconSize(40);
        iconoRegresar.setIconColor(Color.decode("#000000"));
        this.lblRegresar.setIcon(iconoRegresar);
    }

    private Boolean estaTodoBien() {
        String nombre, apellido, documento, correo, telefono, usuario, contrasenna;

        Boolean bandera = true;
        nombre = txtNombre.getText();
        if (nombre.equals("")) {
            txtNombre.requestFocus();
            bandera = false;
            JOptionPane.showMessageDialog(PanelRegistrar, "Digite su nombre", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            apellido = txtApellido.getText();
            if (apellido.equals("")) {
                txtApellido.requestFocus();
                bandera = false;
                JOptionPane.showMessageDialog(PanelRegistrar, "Digite su apellido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                correo = txtCorreo.getText();
                if (correo.equals("")) {
                    txtCorreo.requestFocus();
                    bandera = false;
                    JOptionPane.showMessageDialog(PanelRegistrar, "Digite su correo", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else {
                    telefono = txtTelefono.getText();
                    if (telefono.equals("")) {
                        txtTelefono.requestFocus();
                        bandera = false;
                        JOptionPane.showMessageDialog(PanelRegistrar, "Digite su teléfono", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    } else {
                        usuario = txtUsuario.getText();
                        if (usuario.equals("") || !usuario.equals(txtCorreo.getText())) {
                            txtUsuario.requestFocus();
                            bandera = false;
                            JOptionPane.showMessageDialog(PanelRegistrar, "Digite el usuario con el que va a ingresar al sistema, debe ser igual al correo", "Advertencia", JOptionPane.WARNING_MESSAGE);
                        } else {
                            contrasenna = txtContraseña.getText();
                            if (contrasenna.equals("")) {
                                txtContraseña.requestFocus();
                                bandera = false;
                                JOptionPane.showMessageDialog(PanelRegistrar, "Digite la contraseña con la que va a ingresar al sistema", "Advertencia", JOptionPane.WARNING_MESSAGE);
                            } else {
                                if (cmbRol.getSelectedIndex() == 0) {
                                    bandera = false;
                                    JOptionPane.showMessageDialog(PanelRegistrar, "Por favor seleccione un rol", "Advertencia", JOptionPane.WARNING_MESSAGE);
                                } else {
                                    documento = txtDocumento.getText();
                                    if (documento.equals(" ")) {
                                        txtDocumento.requestFocus();
                                        bandera = false;
                                        JOptionPane.showMessageDialog(PanelRegistrar, "Digite su documento", "Advertencia", JOptionPane.WARNING_MESSAGE);
                                    }
                                }

                            }
                        }

                    }

                }
            }

        }
        return bandera;

    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDocumento.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        cmbRol.setSelectedIndex(0);
        txtUsuario.setText("");
        txtContraseña.setText("");
        txtNombre.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegistrar = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblImagen = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        lblCorreo = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        checkTerminos = new javax.swing.JCheckBox();
        lblAceptar = new javax.swing.JLabel();
        lblAceptar2 = new javax.swing.JLabel();
        lblAceptar3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        panelRegresar = new javax.swing.JPanel();
        lblRegresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelRegistrar.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblNombre.setText("NOMBRE");

        lblApellido.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblApellido.setText("APELLIDO");

        btnIngresar.setBackground(new java.awt.Color(51, 204, 255));
        btnIngresar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("REGISTRAR");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtDocumento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        cmbRol.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su rol", "Laboratorista", "Director" }));

        lblCorreo.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblCorreo.setText("CORREO ELECTRÓNICO");

        lblDocumento.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblDocumento.setText("DOCUMENTO DE IDENTIDAD");

        lblRol.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblRol.setText("ROL");

        lblTelefono.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblTelefono.setText("TELÉFONO");

        checkTerminos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        checkTerminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTerminosActionPerformed(evt);
            }
        });

        lblAceptar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblAceptar.setText("Acepto los");

        lblAceptar2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblAceptar2.setForeground(new java.awt.Color(0, 153, 255));
        lblAceptar2.setText(" Términos y condiciones y políticas ");

        lblAceptar3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblAceptar3.setText("de tratamiento de datos");

        lblUsuario.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblUsuario.setText("USUARIO");

        lblContraseña.setFont(new java.awt.Font("Quando", 0, 16)); // NOI18N
        lblContraseña.setText("CONTRASEÑA");

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtContraseña.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });

        panelRegresar.setBackground(new java.awt.Color(255, 255, 255));
        panelRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelRegresarMouseExited(evt);
            }
        });

        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRegresarLayout = new javax.swing.GroupLayout(panelRegresar);
        panelRegresar.setLayout(panelRegresarLayout);
        panelRegresarLayout.setHorizontalGroup(
            panelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );
        panelRegresarLayout.setVerticalGroup(
            panelRegresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
        PanelRegistrar.setLayout(PanelRegistrarLayout);
        PanelRegistrarLayout.setHorizontalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblCorreo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                                        .addComponent(lblTelefono)
                                        .addGap(106, 106, 106))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRegistrarLayout.createSequentialGroup()
                                        .addComponent(lblUsuario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblRol))
                                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblContraseña))))
                            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(checkTerminos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAceptar3)
                                    .addComponent(lblAceptar2))))
                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelRegistrarLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombre))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblApellido)
                                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblDocumento))
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelRegistrarLayout.setVerticalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(lblRol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkTerminos)
                            .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAceptar)
                                .addComponent(lblAceptar2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAceptar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lblContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (estaTodoBien()) {
            String nombre, apellido, correo, documento, telefono, usuario, contrasenna, acceso;
            nombre = txtNombre.getText();
            apellido = txtApellido.getText();
            documento = txtDocumento.getText();
            correo = txtCorreo.getText();
            telefono = txtTelefono.getText();
            usuario = txtUsuario.getText();
            contrasenna = txtContraseña.getText();
            acceso = cmbRol.getSelectedItem().toString();

            Persona objPersona = new Persona();

            objPersona.setNombrePersona(nombre);
            objPersona.setApellidoPersona(apellido);
            objPersona.setDocumentoPersona(documento);
            objPersona.setCorreoPersona(correo);
            objPersona.setTelefonoPersona(telefono);
            objPersona.setUsuarioPersona(usuario);
            objPersona.setContrasennaPersona(contrasenna);
            objPersona.setNivelAccesoPersona(acceso);

            DaoPersona DaoPers = new DaoPersona();

            if (DaoPers.registrar(objPersona)) {
                JOptionPane.showMessageDialog(PanelRegistrar, "Registro exitoso", "Información", JOptionPane.INFORMATION_MESSAGE);
                FrmPrincipal login = new FrmPrincipal();
                login.setVisible(true);
                this.setVisible(false);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(PanelRegistrar, "No se pudo resgistrar", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void checkTerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTerminosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTerminosActionPerformed

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
//        FrmPrincipal principal = new FrmPrincipal();
//        principal.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void panelRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegresarMouseClicked
        FrmPrincipal login = new FrmPrincipal();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_panelRegresarMouseClicked

    private void panelRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegresarMouseEntered
        panelRegresar.setBackground(Color.decode("#00CCC0"));
        iconoRegresar.setIconColor(Color.decode("#ffffff"));
    }//GEN-LAST:event_panelRegresarMouseEntered

    private void panelRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegresarMouseExited
        panelRegresar.setBackground(Color.decode("#ffffff"));
        iconoRegresar.setIconColor(Color.decode("#000000"));
    }//GEN-LAST:event_panelRegresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrar().setVisible(true);
            }
        });
    }

    public static void setImageToLabel(JLabel lbl, String imagePath) {
        // Cargar la imagen desde el archivo
        ImageIcon imageIcon = new ImageIcon(imagePath);

        // Obtener el ancho y alto del JLabel
        int width = lbl.getWidth();
        int height = lbl.getHeight();

        // Escalar la imagen al tamaño del JLabel
        Image scaledImage = imageIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);

        // Crear un nuevo ImageIcon con la imagen escalada
        ImageIcon scaledIcon = new ImageIcon(scaledImage);

        // Establecer la imagen escalada en el JLabel
        lbl.setIcon(scaledIcon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelRegistrar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JCheckBox checkTerminos;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel lblAceptar;
    private javax.swing.JLabel lblAceptar2;
    private javax.swing.JLabel lblAceptar3;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelRegresar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
